---
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
env:
  browser: true
  es6: true
  node: true
extends:
  - airbnb-base
  - prettier
plugins:
  - import
  - prettier
rules:
  global-require: warn
  import/extensions: [warn, {js: never}]
  import/no-extraneous-dependencies: 'off'
  import/no-named-as-default: 'off'
  prettier/prettier:
    - error
    - {
      singleQuote: true,
      trailingComma: all
    }
settings:
  import/resolver:
    node:
      moduleDirectory:
        - ./
        - ./node_modules
